"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'home',
    'search',
    'flex',
    'streams',
    'site_settings',  
    'subscribers', 
    'blog', 
    'menus',
    'contact',
    'core',
    'storages',

    'wagtail.contrib.forms',
    'wagtail.contrib.modeladmin',
    'wagtail.contrib.routable_page',
    'wagtail.contrib.sitemaps',
    'wagtail.contrib.redirects',
    'wagtail.contrib.settings',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',
    'wagtail.api.v2',

    'modelcluster',
    'taggit',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    'captcha',
    'wagtailcaptcha',
    'rest_framework',
]

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',


    'wagtail.core.middleware.SiteMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'cms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wagtail.contrib.settings.context_processors.settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'cms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',         #python manage.py dbshell
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),   # rm db.sqlite3 then run migrations to clear everything
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

'''
Role	    Create/view drafts	Publish content	Access Settings
Editor	        Yes	            No	            No
Moderator	    Yes	            Yes	            No
Administrator	Yes	            Yes	            Yes
'''

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, 'static'),
]

# ManifestStaticFilesStorage is recommended in production, to prevent outdated
# Javascript / CSS assets being served from cache (e.g. after a Wagtail upgrade).
# See https://docs.djangoproject.com/en/2.2/ref/contrib/staticfiles/#manifeststaticfilesstorage
#STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'


STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Wagtail settings

WAGTAIL_SITE_NAME = "cms"

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
BASE_URL = 'http://legalaid.site'


#[default]
aws_access_key_id='AKIAIIG57XYNGEQ63FOQ'
aws_secret_access_key='G9fY/SuwE0SnwRQcQfBQ6e9lgvGmywPirRz8PItBTwEZs'
#aws_session_token='FwoGZXIvYXdzEJ3//////////wEaDPD3KFhdqZ6NnKrPkSLJAQHoV5iSxp4fckCaYihCxlM2X0fzZDNMRjNn+/iJOgNe8vGzz8/RC6Ree56l0ogeyehcuJmdCQKMDE/ABbmg2G3xWLJhlUY69aizjIUcIHsxLkv6lCmq/bMRznmHrV8txRbnQQd7A3F69IrtDA6795FkoGaWgJ+dYv/l0Iezw8NY1BhY+Pl9lYKKdnyNg/LQPdgaO9/20UWrFfaIrXXX1gblscMXdoFa8qx/rxWllmMwnFlwdcEgFM6hU4L2Hxrydn8oA7rHUzOG8Ci666j0BTItMhTbuH0X7YKBeidvUFdKgp1TInDmCt4PdcwyQp8AgbqRQvX0gEFWAmyLmXye'

AWS_S3_CUSTOM_DOMAIN = 'legalaid.site'
AWS_STORAGE_BUCKET_NAME = 'wagtailcms'
AWS_S3_REGION_NAME = 'ap-south-1'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.ap-south-1.amazonaws.com' % AWS_STORAGE_BUCKET_NAME


STATICFILES_STORAGE = DEFAULT_FILE_STORAGE
STATIC_URL = "https://{}/static/".format(AWS_S3_CUSTOM_DOMAIN)
MEDIA_URL = "https://{}/media/".format(AWS_S3_CUSTOM_DOMAIN)


RECAPTCHA_PUBLIC_KEY = "6LcThOQUAAAAAEs_IKKeWBxSnFkb6seSVMMxLWzS"
RECAPTCHA_PRIVATE_KEY = "6LcThOQUAAAAAMSnaSI_l_OifnMsh_E47apIkPtT"
NOCAPTCHA = True



