# Generated by Django 2.2.9 on 2020-01-28 16:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add your text in here', required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='add additional text', required=True))]))], blank=True, null=True),
        ),
    ]
