# Generated by Django 3.0.3 on 2020-04-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='youtube',
            new_name='Instagram',
        ),
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='facebook',
            new_name='Linkedin',
        ),
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='twitter',
            new_name='Twitter',
        ),
    ]
